window:
  dimensions:
    columns: 84
    lines: 36

  padding:
    x: 8
    y: 8
  decorations: buttonless

draw_bold_text_with_bright_colors: false

font:
  normal:
    family: Anonymous Pro
    style: Regular

  bold:
    family: Anonymous Pro
    style: Bold

  italic:
    family: Anonymous Pro
    style: Italic

  size: 16.0

  offset:
    x: 0
    y: 8

  glyph_offset:
    x: 0
    y: 6

  use_thin_strokes: true

render_timer: false

custom_cursor_colors: true

colors:
  primary:
    background: '0xffffff'
    foreground: '0x6c696e'

  cursor:
    text: '0xffffff'
    cursor: '0x6c696e'

  normal:
    black:   '0xffffff'
    red:     '0xd8137f'
    green:   '0x17ad98'
    yellow:  '0xdc8a0e'
    blue:    '0x775dff'
    magenta: '0xaa17e6'
    cyan:    '0x149bda'
    white:   '0x6c696e'

  bright:
    black:   '0xa7a5a8'
    red:     '0xd65407'
    green:   '0xe1e1e2'
    yellow:  '0xc4c3c5'
    blue:    '0x89878b'
    magenta: '0x4f4b51'
    cyan:    '0xe013d0'
    white:   '0x6c696e'

bell:
  animation: EaseOutExpo
  duration: 100
  color: '0xa7a5a8'


live_config_reload: true

shell:
  program: zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
